spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teaching_plan?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 200Mb

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xinwei.teachingplan.mapper

logging:
  level:
    com:
      example:
        mapper: debug
img:
  path: E:\WorkData