spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    username: chengfei
#    data-password: cheng2108638
#    url: jdbc:mysql://47.112.115.39:3306/teaching_plan?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    url: jdbc:mysql://123.56.181.200:3306/njwd_cost5?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: yican
    password: iRhMW8B3Vz#

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xinwei.teachingplan.mapper

logging:
  level:
    com:
      example:
        mapper : debug